flow_name = "SimpleFlow"
flow_version = "0.0.1"
flow_id = "uuid"
description = "A simple flow that echos holiday cheer"

# Global variables
variables = []

[trigger]
name = "file_change"

[trigger.settings]
file = "/Users/auser/Desktop/watch-directory"

[[nodes]]
name = "echocheer"
label = "Holiday cheers"
depends_on = []
variables = [{ cheers = "Jingle Bells" }]

[nodes.action]
action_type = "Shell"

[nodes.action.config]
command = "echo 'Jingle Bells'"


[[nodes]]
name = "say-cheers"
label = "say holiday cheer"
depends_on = ["echocheer"]
variables = [{ cheer = "{{echocheer.stdout}}" }]

[nodes.action]
action_type = "Shell"

[nodes.action.config]
command = "echo 'Heres my cheers: {{cheer}}'"
executor = "/bin/bash"
args = []


[[nodes.environment]]
NODE_ENV = "development"
